version: "3"

services:
  confd:
    build: ./confd
    volumes:
      - ./target:/target
      - $HOME/.aws:/root/.aws
    environment:
      - AWS_PROFILE
      - ADD_PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
